// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void CT02CamposCor() {
    driver.Navigate().GoToUrl("https://rafajms.github.io/ProjetoAlmoxarifadoMain/?authuser=0");
    driver.Manage().Window.Size = new System.Drawing.Size(945, 1012);
    driver.FindElement(By.Id("idDepartamento")).Click();
    driver.FindElement(By.Id("departamento")).Click();
    driver.FindElement(By.Id("dataRequisicao")).Click();
    driver.FindElement(By.Id("idFuncionario")).Click();
    driver.FindElement(By.Id("NomeFuncionario")).Click();
    driver.FindElement(By.Id("cargo")).Click();
    driver.FindElement(By.Id("categoriaMotivo")).Click();
    driver.FindElement(By.Id("Motivo")).Click();
    driver.FindElement(By.Id("CodigoProtudo")).Click();
    driver.FindElement(By.Id("DescricaoProtudo")).Click();
    driver.FindElement(By.Id("Quantidade")).Click();
  }
}
