// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void CT04e05CategoriaMotivo() {
    driver.Navigate().GoToUrl("https://rafajms.github.io/ProjetoAlmoxarifadoMain/?authuser=0");
    driver.Manage().Window.Size = new System.Drawing.Size(945, 1012);
    driver.FindElement(By.Id("idDepartamento")).Click();
    driver.FindElement(By.CssSelector(".camposPrincipaisLinha3")).Click();
    driver.FindElement(By.Id("Motivo")).Click();
    driver.FindElement(By.Id("categoriaMotivo")).Click();
    {
      var dropdown = driver.FindElement(By.Id("categoriaMotivo"));
      dropdown.FindElement(By.XPath("//option[. = 'Gestão']")).Click();
    }
    driver.FindElement(By.Id("Motivo")).Click();
    {
      var dropdown = driver.FindElement(By.Id("Motivo"));
      dropdown.FindElement(By.XPath("//option[. = 'Equipamento Permanente']")).Click();
    }
  }
}
